<a href="https://colab.research.google.com/github/anuj-l22/PyTorch_ZTM/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.3.1+cu121


## Introduction to Tensors

### Creating tensors
PyTorch Tensors are created using torch.tensor

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7 , 8] ,
                       [9 , 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[10,11,12],
                        [13,14,15],
                        [16,17,18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they startb with tensors full of random numbers and then adjust those random numbers to better represent the data


In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height,weight,color channels
random_image_size_tensor.size , random_image_size_tensor.shape, random_image_size_tensor.ndim

(<function Tensor.size>, torch.Size([3, 224, 224]), 3)

In [ ]:
# Creating my own random tensor
# Note : Size is default parameter in rand
random_tensor_2 = torch.rand(size = (2,3,3) )
random_tensor_2

tensor([[[0.5745, 0.9200, 0.3230],
         [0.8613, 0.0919, 0.3102],
         [0.9536, 0.6002, 0.0351]],

        [[0.6826, 0.3743, 0.5220],
         [0.1336, 0.9666, 0.9754],
         [0.8474, 0.8988, 0.1105]]])

In [ ]:
random_tensor_2.shape,random_tensor_2.ndim

(torch.Size([2, 3, 3]), 3)

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() is depricated so use torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start = 1, end = 11 , step = 1.)
one_to_ten

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten.dtype

torch.float32

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor datatypes
**Note: Tensor datatypes may lead to error**
1. Tensors not right datatype (Not necesssarily all operations)
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# Floar 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # What datatype is the tensor
                               device = None, # What device is your tensor on , None or "cuda"
                               requires_grad = False) # Whether or not to track gradients with tensors operations
float_32_tensor , float_32_tensor.dtype,float_32_tensor.shape

(tensor([3., 6., 9.]), torch.float32, torch.Size([3]))

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9] , dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors

1. Tensors not right datatype- to do get datatype from a tensor , can use tensor.dtype
2. Tensors not right shape- to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device- to get device from a tensor, can use tensor.device

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4563, 0.9719, 0.3968, 0.1496],
        [0.4743, 0.9973, 0.4436, 0.9726],
        [0.5194, 0.5337, 0.7050, 0.3362]])

In [ ]:
# size is a function whereas shape is an attribute
some_tensor.size() , some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
# Find out details about some tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Size of tensor: {some_tensor.shape}")
print(f"Device is on: {some_tensor.device}")

tensor([[0.4563, 0.9719, 0.3968, 0.1496],
        [0.4743, 0.9973, 0.4436, 0.9726],
        [0.5194, 0.5337, 0.7050, 0.3362]])
Datatype of tensor: torch.float32
Size of tensor: torch.Size([3, 4])
Device is on: cpu


### Bonus: Try to find how to change device type and datatype in random

## Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor
tensor*10 # Because no reassignment

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtratct from tensor
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Twi main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* '(3,2) @ (3,2)' wont work
* '(2,3) @ (3,2)' will work
2. The resulting matrix has the shpe of the outer dimensions

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.2618, 0.8054],
        [0.3966, 1.0432]])

In [ ]:
# Element wise multiplication
print(tensor, "*" , tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor@tensor

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]* tensor[i]
print(value)

tensor(14)
CPU times: user 1.98 ms, sys: 0 ns, total: 1.98 ms
Wall time: 6.17 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)
# Way faster because vectorized

CPU times: user 86 µs, sys: 0 ns, total: 86 µs
Wall time: 89.9 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A,tensor_B) # Short for matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues,we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# Matrix multiplicatio operation works when tensor_B is transposed
output = torch.mm(tensor_A,tensor_B.T)
print(f"Output : {output}")
print(f"\nOutput shape: {output.shape}"  )


Output : tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min,max,mean,sum,etc (tensor aggregation)

In [ ]:
# Create a tensor
X = torch.arange(1,100,10)
X

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min
torch.min(X) , X.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(X) , X.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean
torch.mean(X.type(torch.float32)) , X.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(X) , X.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [ ]:
X

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has minimum value with argmin and returns position of target tensor
X.argmin()

tensor(0)

In [ ]:
X[0]

tensor(1)

In [ ]:
# Find position in tensor that has maximum value with argmax()
X.argmax()

tensor(9)

In [ ]:
X[9]

tensor(91)

## Reshaping , stacking , squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Retuen a view of an input tensor of certain shape but keep the same memoey as original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
torch.tensor(5).shape

torch.Size([])

In [ ]:
# Let's create a tensor
x = torch.arange(1.,10.)
x , x.shape , x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape,x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [ ]:
# Change the view
z = x.view(9,1)
z , z.shape , z.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 2)

In [ ]:
# Changing z changes x because the view of a tensor shares the same memory as the original tensor
# z[:,0] = 5
z,x

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other , dim 0 (side by side) , dim 1 (top by top)
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
x_squeezed = x.squeeze()
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x.unsqueeze(dim = 1)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor : tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [ ]:
# torch.permute - rearranges the dimensions of target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height,width,color channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # Shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original , x_permuted

(tensor([[[0.8973, 0.3629, 0.1748],
          [0.2401, 0.5457, 0.7303],
          [0.5268, 0.6694, 0.3213],
          ...,
          [0.6444, 0.1292, 0.1217],
          [0.5528, 0.4964, 0.9242],
          [0.0081, 0.1417, 0.3316]],
 
         [[0.9119, 0.3328, 0.2795],
          [0.1215, 0.8850, 0.2981],
          [0.9226, 0.7043, 0.1120],
          ...,
          [0.3077, 0.3311, 0.0851],
          [0.3749, 0.9226, 0.7304],
          [0.7855, 0.4110, 0.9457]],
 
         [[0.2304, 0.1058, 0.8803],
          [0.9300, 0.8196, 0.9411],
          [0.8514, 0.8218, 0.8381],
          ...,
          [0.3988, 0.2674, 0.4848],
          [0.4783, 0.3343, 0.8818],
          [0.7410, 0.9672, 0.1386]],
 
         ...,
 
         [[0.4126, 0.7277, 0.0116],
          [0.6052, 0.1573, 0.0948],
          [0.2078, 0.5103, 0.1247],
          ...,
          [0.2716, 0.1508, 0.9370],
          [0.7491, 0.9331, 0.1751],
          [0.6018, 0.6851, 0.4115]],
 
         [[0.9589, 0.3535, 0.6676],
          [0

In [ ]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (Selecting data from tensors)

Indexing with PyTorch is similar to indexing from NumPy

### Indexing goes from outer bracket to inner bracket

In [ ]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket
x[0][0] , x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0] , x[0,0,0 ]

(tensor(1), tensor(1))

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
# Note how no of square brackets change in different situations
x[:,1,1] , x[:,:,1]

(tensor([5]), tensor([[2, 5, 8]]))

In [ ]:
# Get all values of the 0 dimensions but only the 1 index value of 1st and 2nd dimension
x[:,1,1] , x[:,1,:]

(tensor([5]), tensor([[4, 5, 6]]))

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[0,2,2])

# Index on x to return 3,6,9
## Important note on how boxed slicing yields different results
print(x[0][:][2])
print(x[0,:,2])
print(x[0][:, 2])

tensor(9)
tensor([7, 8, 9])
tensor([3, 6, 9])
tensor([3, 6, 9])


## PyTorch tensors and NumPy

Numpy is a popular scientific Python numerical computing library

And because of this , PyTorch has functionality to interact with it

* Data in NumPy , want in PyTorch tensor -> `torch.Tensor.numpy(ndarray)`
* PyTorch tensor -> `torch.Tensor.numpy()`




In [ ]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warnings when converting from numpy-> PyTorch , PyTorch displays Numpy's default datatype of float64 unless specified otherwise
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
torch.arange(2.,8.).dtype

torch.float32

In [ ]:
array.dtype

dtype('float64')

In [ ]:
# Change the value of array , what will this do to 'tensor'?

array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor , what happens to 'numpy_tensor'
tensor = tensor + 1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`starts with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again... `

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**
Essentially what the random seed does is 'flavour' the randomess
So essentially we are doing pseudo-randomness

In [ ]:
randmom_tensor_A= torch.rand(3,4)
randmom_tensor_B= torch.rand(3,4)
print(randmom_tensor_A)
print(randmom_tensor_B)
print( randmom_tensor_A == randmom_tensor_B)

tensor([[0.1488, 0.0913, 0.4470, 0.2440],
        [0.5571, 0.1928, 0.0602, 0.5837],
        [0.0009, 0.7581, 0.5817, 0.4338]])
tensor([[0.0333, 0.3746, 0.7110, 0.5946],
        [0.9475, 0.6228, 0.0768, 0.7122],
        [0.3727, 0.8434, 0.7186, 0.8834]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

# Set the random seed
# Need to use seed everytime before assignment
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])



### 1. Getting a GPU

You may already know what's going on when I say GPU. But if not, there are a few ways to get access to one.

| **Method** | **Difficulty to setup** | **Pros** | **Cons** | **How to setup** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Easy | Free to use, almost zero setup required, can share work with others as easy as a link | Doesn't save your data outputs, limited compute, subject to timeouts | [Follow the Google Colab Guide](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Use your own | Medium | Run everything locally on your own machine | GPUs aren't free, require upfront cost | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/locally/) |
| Cloud computing (AWS, GCP, Azure) | Medium-Hard | Small upfront cost, access to almost infinite compute | Can get expensive if running continually, takes some time to setup right | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/cloud-partners/) |

To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the `!` (also called bang) means "run this on the command line".



In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic codes
E.g. Run n GPU if available else CPU

In [225]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [226]:
# Count the number of devices
torch.cuda.device_count()

0

###3. Putting tensors (and models) on the GPU
The reason for this is that GPU does faster computations

In [227]:
# Setup a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor , tensor.device)

tensor([1, 2, 3]) cpu


In [230]:
# Move tensor to GPU(if available)
# Will work if GPU available
tensor_on_gpu= tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

###4. Moving tensors back to CPU

In [231]:
# If tensor is on GPU . can't transform to Numpy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [232]:
# To fix the GPU tensor (if you have obe) with Numpy issue , we can first set it to the CPU
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])